<a href="https://colab.research.google.com/github/hrcn81/AIML-Workshop/blob/main/AIML_Workshop_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

In [3]:
list1 = [10,21,23,44,51]        # Python is sensitive to brackets as well

a = np.array(list1)

a

array([10, 21, 23, 44, 51])

In [4]:
type(a)

numpy.ndarray

# 2D Array

In [5]:
a = np.array([[12,4,5],[23,45,66],[45,34,23]])

a

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [6]:
a.ndim

2

In [7]:
a.shape

(3, 3)

In [8]:
a.size

9

In [9]:
a.itemsize              # Size of each elements in bytes

8

In [10]:
a.dtype

dtype('int64')

In [11]:
a[0]

array([12,  4,  5])

In [12]:
a[2]

array([45, 34, 23])

In [13]:
a[-1]

array([45, 34, 23])

In [14]:
a[0:]                   # All rows from index 0

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [15]:
a[1:]

array([[23, 45, 66],
       [45, 34, 23]])

In [16]:
a[-2:]

array([[23, 45, 66],
       [45, 34, 23]])

In [17]:
a[:2]

array([[12,  4,  5],
       [23, 45, 66]])

In [18]:
a[1,1]

45

In [19]:
a[:,2]

array([ 5, 66, 23])

In [20]:
# Generates equidistant numbers b/w some range

np.linspace(1,100,100)              # (start,end,number_of_elements_you_want)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [21]:
a = np.arange(1,102,5)
# len(a)          # 21
a

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101])

In [22]:
a.min()

1

In [23]:
a.max()

101

In [24]:
a.mean()

51.0

In [25]:
a.sum()

1071

In [26]:
a.argmax()

20

In [27]:
a.argmin()

0

In [28]:
a = np.array([[12,4,5],[23,45,66],[45,34,23]])

a

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23]])

In [29]:
a.sum()

257

In [30]:
a.sum(axis = 1)             # (2-D) for addition of rows(horizontal) axis = 1

array([ 21, 134, 102])

In [31]:
a.sum(axis = 0)             # (2-D) for addition of columns(verticle) axis = 0

array([80, 83, 94])

# Concatination of arrays

In [32]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.vstack((a,b))

array([[12,  4,  5],
       [23, 45, 66],
       [45, 34, 23],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [34]:
np.hstack((a,b))

array([[12,  4,  5,  1,  2,  3],
       [23, 45, 66,  4,  5,  6],
       [45, 34, 23,  7,  8,  9]])

In [35]:
zero = np.zeros(4)

zero

array([0., 0., 0., 0.])

In [36]:
zero = np.zeros((4,4))

zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
ones = np.ones(5)

ones

array([1., 1., 1., 1., 1.])

In [38]:
ones = np.ones((4,4))

ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
ones*10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [40]:
ones.dtype

dtype('float64')

In [41]:
on = ones.astype('int')

on

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
on.dtype

dtype('int64')

# Random Numbers

In [43]:
np.random.randint(10,100,20)

array([54, 60, 51, 31, 53, 77, 22, 38, 63, 85, 65, 56, 61, 41, 47, 58, 93,
       92, 83, 45])

In [44]:
np.random.seed(2)
np.random.randint(10,100,20)

array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59, 85, 95, 57, 73, 41, 30, 47,
       49, 77, 14])

In [45]:
np.random.seed(3)
np.random.randint(10,100,(3,3))

array([[34, 13, 66],
       [82, 10, 31],
       [29, 84, 51]])

In [46]:
np.random.seed(2)

a = np.random.randint(10,100,(3,4))

a

array([[50, 25, 82, 32],
       [53, 92, 85, 17],
       [44, 59, 85, 95]])

In [47]:
a.reshape(4,3)

array([[50, 25, 82],
       [32, 53, 92],
       [85, 17, 44],
       [59, 85, 95]])

In [48]:
a.reshape(2,6)

array([[50, 25, 82, 32, 53, 92],
       [85, 17, 44, 59, 85, 95]])

In [49]:
a.reshape(6,2)

array([[50, 25],
       [82, 32],
       [53, 92],
       [85, 17],
       [44, 59],
       [85, 95]])

In [50]:
a.reshape(12,-1)

array([[50],
       [25],
       [82],
       [32],
       [53],
       [92],
       [85],
       [17],
       [44],
       [59],
       [85],
       [95]])

In [51]:
a.reshape(-1,12)

array([[50, 25, 82, 32, 53, 92, 85, 17, 44, 59, 85, 95]])